### ISSUE TITLE
[ENHANCEMENT] make package compatible with Magento 2.4.0

### ISSUE THREAD

**Issue by stigmi-man** [opengento/magento2-gdpr#50]
## Description

Please make the package compatible with Magento 2.4.0

## Prerequisites  

**PHP Version:**
 - 7.4.0

**Magento Version:**
 - 2.4.0

## Issue Details

Could not find a version of package opengento/module-gdpr matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by thomas-kl1** [comment]
hi @stigmi-man, latest head of master is compatible with Magento 2.4.0, if you need to test

**Comment by stigmi-man** [comment]
`composer require opengento/module-gdpr`
![image](https://user-images.githubusercontent.com/45425264/99804259-03b21780-2b3b-11eb-9ad7-5adf4353d8f2.png)
and I don't want to change my global config (minimum-stability) :/

**Comment by thomas-kl1** [comment]
@stigmi-man I released 4.0.0-alpha if you need to test. Please feedback any issues :)

**Comment by stigmi-man** [comment]
I still have the error with `composer require opengento/module-gdpr` (with magento v2.4.1)

**Comment by bbtimx** [comment]
> I still have the error with composer require opengento/module-gdpr (with magento v2.4.1)

Same problem!

**Comment by thomas-kl1** [comment]
@stigmi-man @bbtimx I tried `composer require opengento/module-gdpr 4.0.0-alpha` and it was working fine on Magento 2.4 project. Could you try with the option `-vvv` and shoot me the reason why it fails?

**Comment by thomas-kl1** [comment]
@stigmi-man @bbtimx feel free to reopen if the issues still occurs on your side.
