### ISSUE TITLE
Compatibility with Magento 2.3

### ISSUE THREAD

**Issue by antoniocarboni** [opengento/magento2-gdpr#56]
is it possible to make the composer side installation requirements less stricted to allow compatibility with magento 2.3?
Actually  "magento/framework": "^103.0" require a version of laminas-code 3.4.1 which is used in 2.4 but isn't compatible with 2.3 (which require laminas-code 3.3)

is possible to replace the version of magento/framework with this version?

 "magento/framework": "^102.0||^103.0",

Thanks

**Comment by thomas-kl1** [comment]
Hi, actually the master branch is only 2.4 compatible (escaper in templates, controller action refactoring...). I can look to backward other changes to the 2.3 branche. I update you later 😊

**Comment by lukawefocus** [comment]
@thomas-kl1 are you still looking into this. Just tried 2.3 branche on Magento 2.3.5. I get the following error on personal data export:

`Fatal error: Uncaught Error: Cannot unpack array with string keys in /home/*****/public_html/app/code/Opengento/Gdpr/Model/Action/PerformedBy/NotEmptyStrategy.php:29 Stack trace: #0 /home/*****/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Opengento\Gdpr\Model\Action\PerformedBy\NotEmptyStrategy->__construct(Array) #1 /home/*****/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Opengento\\Gdpr\\...', Array) #2 /home/*****/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Opengento\\Gdpr\\...') #3 /home/*****/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Opengento\\Gdpr\\...') #4 /home/*****/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractF in /home/*****/public_html/app/code/Opengento/Gdpr/Model/Action/PerformedBy/NotEmptyStrategy.php on line 29`

**Comment by thomas-kl1** [comment]
@lukawefocus @antoniocarboni could you check with latest changes of magento2.3.x branch?

**Comment by lukawefocus** [comment]
@thomas-kl1 

Export button in customer account (frontend) works. It shows: 

"Your personal data document is pending export." I guess this will be handled by a cron?

However export Personel Data in admin customer view throws an error:

`
Fatal error: Uncaught TypeError: Argument 1 passed to Opengento\Gdpr\Model\Entity\EntityValue\StrategyProcessor::process() must be of the type string, object given, called in /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/EntityIterator.php on line 50 and defined in /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/EntityValue/StrategyProcessor.php:25 Stack trace: #0 /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/EntityIterator.php(50): Opengento\Gdpr\Model\Entity\EntityValue\StrategyProcessor->process(Object(Magento\Customer\Model\Data\Customer), 'id', 24) #1 /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/DataCollector.php(32): Opengento\Gdpr\Model\Entity\EntityIterator->iterate(Object(Magento\Customer\Model\Data\Customer)) #2 /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/DataCollectorGeneric.php(49): Opengento\Gdpr\Model\Entity\DataCollector->collect(Object(Magento\Customer\Model\Data\Customer)) #3 /home/******/p in /home/******/public_html/app/code/Opengento/Gdpr/Model/Entity/EntityValue/StrategyProcessor.php on line 25`

**Comment by lukawefocus** [comment]
@thomas-kl1 If you want I can give you access to a fresh instance of magento 2.3.5 with this module enabled so you can test. Just let me know

**Comment by thomas-kl1** [comment]
@lukawefocus thank you for the tests, I've fixed the error, my bad it was due to a refactoring of a method signature

**Comment by lukawefocus** [comment]
@thomas-kl1Unfortunatly data export still doesn't work. Downloading from admin > customer edit page shows a blank page now. I found an exception in the log (below). This module depends on another module to create the Pdf? 

`[2020-12-23 14:40:15] main.DEBUG: Source class "\mikehaertl\wkhtmlto\Pdf" for "mikehaertl\wkhtmlto\PdfFactory" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class \"\\mikehaertl\\wkhtmlto\\Pdf\" for \"mikehaertl\\wkhtmlto\\PdfFactory\" generation does not exist. at /home/[2020-12-23 14:40:15] main.DEBUG: Source class "\mikehaertl\wkhtmlto\Pdf" for "mikehaertl\wkhtmlto\PdfFactory" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class \"\\mikehaertl\\wkhtmlto\\Pdf\" for \"mikehaertl\\wkhtmlto\\PdfFactory\" generation does not exist. at /home/*****/public_html/lib/internal/Magento/Framework/Code/Generator.php:222)"} []
[2020-12-23 14:40:15] main.CRITICAL: Exception message: Class mikehaertl\wkhtmlto\PdfFactory does not exist
Trace: <pre>#1 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() called at [lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:48]
#2 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70]
#3 Magento\Framework\ObjectManager\ObjectManager->get() called at [app/code/Opengento/Gdpr/Service/Export/RendererFactory.php:47]
#4 Opengento\Gdpr\Service\Export\RendererFactory->get() called at [app/code/Opengento/Gdpr/Model/Export/ExportToFile.php:71]
#5 Opengento\Gdpr\Model\Export\ExportToFile->export() called at [app/code/Opengento/Gdpr/Model/ExportEntityManagement.php:96]
#6 Opengento\Gdpr\Model\ExportEntityManagement->export() called at [app/code/Opengento/Gdpr/Model/Export/ExportEntityData.php:69]
#7 Opengento\Gdpr\Model\Export\ExportEntityData->export() called at [app/code/Opengento/Gdpr/Model/Action/Export/CreateOrExportAction.php:40]
#8 Opengento\Gdpr\Model\Action\Export\CreateOrExportAction->execute() called at [app/code/Opengento/Gdpr/Model/Action/ActionComposite.php:104]
#9 Opengento\Gdpr\Model\Action\ActionComposite->process() called at [app/code/Opengento/Gdpr/Model/Action/ActionComposite.php:78]
#10 Opengento\Gdpr\Model\Action\ActionComposite->execute() called at [app/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export.php:67]
#11 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export->executeAction() called at [app/code/Opengento/Gdpr/Controller/Adminhtml/AbstractAction.php:37]
#12 Opengento\Gdpr\Controller\Adminhtml\AbstractAction->execute() called at [generated/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export/Interceptor.php:24]
#13 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->execute() called at [lib/internal/Magento/Framework/App/Action/Action.php:108]
#14 Magento\Framework\App\Action\Action->dispatch() called at [app/code/Magento/Backend/App/AbstractAction.php:231]
#15 Magento\Backend\App\AbstractAction->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#16 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#17 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Magento/Backend/App/Action/Plugin/Authentication.php:143]
#18 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:135]
#19 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#20 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->___callPlugins() called at [generated/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export/Interceptor.php:39]
#21 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/FrontController.php:162]
#22 Magento\Framework\App\FrontController->processRequest() called at [lib/internal/Magento/Framework/App/FrontController.php:98]
#23 Magento\Framework\App\FrontController->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#24 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/Http.php:116]
#28 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#29 Magento\Framework\App\Http\Interceptor->launch() called at [lib/internal/Magento/Framework/App/Bootstrap.php:261]
#30 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre> [] []/public_html/lib/internal/Magento/Framework/Code/Generator.php:222)"} []
[2020-12-23 14:40:15] main.CRITICAL: Exception message: Class mikehaertl\wkhtmlto\PdfFactory does not exist
Trace: <pre>#1 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() called at [lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:48]
#2 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70]
#3 Magento\Framework\ObjectManager\ObjectManager->get() called at [app/code/Opengento/Gdpr/Service/Export/RendererFactory.php:47]
#4 Opengento\Gdpr\Service\Export\RendererFactory->get() called at [app/code/Opengento/Gdpr/Model/Export/ExportToFile.php:71]
#5 Opengento\Gdpr\Model\Export\ExportToFile->export() called at [app/code/Opengento/Gdpr/Model/ExportEntityManagement.php:96]
#6 Opengento\Gdpr\Model\ExportEntityManagement->export() called at [app/code/Opengento/Gdpr/Model/Export/ExportEntityData.php:69]
#7 Opengento\Gdpr\Model\Export\ExportEntityData->export() called at [app/code/Opengento/Gdpr/Model/Action/Export/CreateOrExportAction.php:40]
#8 Opengento\Gdpr\Model\Action\Export\CreateOrExportAction->execute() called at [app/code/Opengento/Gdpr/Model/Action/ActionComposite.php:104]
#9 Opengento\Gdpr\Model\Action\ActionComposite->process() called at [app/code/Opengento/Gdpr/Model/Action/ActionComposite.php:78]
#10 Opengento\Gdpr\Model\Action\ActionComposite->execute() called at [app/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export.php:67]
#11 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export->executeAction() called at [app/code/Opengento/Gdpr/Controller/Adminhtml/AbstractAction.php:37]
#12 Opengento\Gdpr\Controller\Adminhtml\AbstractAction->execute() called at [generated/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export/Interceptor.php:24]
#13 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->execute() called at [lib/internal/Magento/Framework/App/Action/Action.php:108]
#14 Magento\Framework\App\Action\Action->dispatch() called at [app/code/Magento/Backend/App/AbstractAction.php:231]
#15 Magento\Backend\App\AbstractAction->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#16 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#17 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Magento/Backend/App/Action/Plugin/Authentication.php:143]
#18 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:135]
#19 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#20 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->___callPlugins() called at [generated/code/Opengento/Gdpr/Controller/Adminhtml/Privacy/Export/Interceptor.php:39]
#21 Opengento\Gdpr\Controller\Adminhtml\Privacy\Export\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/FrontController.php:162]
#22 Magento\Framework\App\FrontController->processRequest() called at [lib/internal/Magento/Framework/App/FrontController.php:98]
#23 Magento\Framework\App\FrontController->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#24 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/Http.php:116]
#28 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#29 Magento\Framework\App\Http\Interceptor->launch() called at [lib/internal/Magento/Framework/App/Bootstrap.php:261]
#30 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre> [] []`

**Comment by thomas-kl1** [comment]
Yes, the module should be installed with composer so the dependencies are all set. A third party library is used to generate easily PDF from html, so you can override it in order to fit your needs.

**Comment by thomas-kl1** [comment]
@lukawefocus you know what, I think I'll replace this package with tcpdf which is standalone

**Comment by lukawefocus** [comment]
@thomas-kl1 thanks for pointing that out. I've installed all dependencies using composer. PDF worked in admin, however it's printing the left menu bar of magento admin panel in the PDF. In the front the export did not work, failed on buidling the zip file > PDF was missing. Anyway, I'll disable PDF and use HTML as human readable version, however the PDF will need some kind of refactoring especially because the complex PDF writer dependancy. 

I'll test all other features later today and let you know if the compatibility with 2.3.5 and 2.3.5.-p1 is ok

**Comment by thomas-kl1** [comment]
@lukawefocus I've opened a new ticket #68 regarding the PDF & HTML issues.

**Comment by lukawefocus** [comment]
Hi @thomas-kl1,

I've commited a few lines in 2.3 branch to get the module working, now final issue is the erasure of data. Starting the erasure proces and confirming by password now works, Then you wait for the delay and cron to run the erasure. I just ran the cron (4 days later) manually and the following happend: 

-Account Privacy Settings page refreshed with message: **Your account cannot be erased while you have pending orders.**
-no orders have been deleted or anonymised (actually don't know what to expect here)
-account postal address has been anonymised, name and email adress have not (also don't know if they should or not)
-account hasn't been deleted

Module settings are default. This account has no panding orders. It wouldn't be possible to request the erasure in first place if it had. All orders of this account have the status Completed or Closed and they are marked as safe to delete in the settings.

It's impossible to request the erasure again and the account shows false message about pending orders which do not exist.

Debug file shows the following error during the cron run. I hope it's an easy fix and you can find it.

`Impossible to process the erasure: Warning: SessionHandler::destroy(): Session is not active in /home/*****/public_html/vendor/magento/framework/Session/SaveHandler.php on line 138 [{"file":"/home/*****/public_html/vendor/opengento/module-gdpr/Cron/EraseEntity.php","line":89,"function":"process","class":"Opengento\\Gdpr\\Model\\EraseEntityManagement","type":"->","args":["[object] (Opengento\\Gdpr\\Model\\EraseEntity: {})"]},{"function":"execute","class":"Opengento\\Gdpr\\Cron\\EraseEntity","type":"->","args":["[object] (Magento\\Cron\\Model\\Schedule: {})"]},{"file":"/home/*****/public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php","line":350,"function":"call_user_func_array","args":[["[object] (Opengento\\Gdpr\\Cron\\EraseEntity: {})","execute"],["[object] (Magento\\Cron\\Model\\Schedule: {})"]]},{"file":"/home/*****/public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php","line":809,"function":"_runJob","class":"Magento\\Cron\\Observer\\ProcessCronQueueObserver","type":"->","args":[1609149780,1609149816,{"name":"gdpr_erase_entity","instance":"Opengento\\Gdpr\\Cron\\EraseEntity","method":"execute","config_path":"gdpr/erasure/entity_schedule"},"[object] (Magento\\Cron\\Model\\Schedule: {})","gdpr"]},{"file":"/home/*****/public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php","line":776,"function":"tryRunJob","class":"Magento\\Cron\\Observer\\ProcessCronQueueObserver","type":"->","args":[1609149780,1609149816,{"name":"gdpr_erase_entity","instance":"Opengento\\Gdpr\\Cron\\EraseEntity","method":"execute","config_path":"gdpr/erasure/entity_schedule"},"[object] (Magento\\Cron\\Model\\Schedule: {})","gdpr"]},{"file":"/home/*****/public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php","line":267,"function":"processPendingJobs","class":"Magento\\Cron\\Observer\\ProcessCronQueueObserver","type":"->","args":["gdpr",{"gdpr_erase_entity":{"name":"gdpr_erase_entity","instance":"Opengento\\Gdpr\\Cron\\EraseEntity","method":"execute","config_path":"gdpr/erasure/entity_schedule"},"gdpr_erase_entity_scheduler":{"name":"gdpr_erase_entity_scheduler","instance":"Opengento\\Gdpr\\Cron\\EraseEntityScheduler","method":"execute","config_path":"gdpr/erasure/entity_max_age_schedule"},"gdpr_export_entity":{"name":"gdpr_export_entity","instance":"Opengento\\Gdpr\\Cron\\ExportEntity","method":"execute","config_path":"gdpr/export/entity_schedule"},"gdpr_export_entity_expired":{"name":"gdpr_export_entity_expired","instance":"Opengento\\Gdpr\\Cron\\ExportEntityExpired","method":"execute","config_path":"gdpr/export/entity_expired_schedule"}},1609149816]},{"file":"/home/*****/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php","line":88,"function":"execute","class":"Magento\\Cron\\Observer\\ProcessCronQueueObserver","type":"->","args":["[object] (Magento\\Framework\\Event\\Observer: {})"]},{"file":"/home/*****/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php","line":74,"function":"_callObserverMethod","class":"Magento\\Framework\\Event\\Invoker\\InvokerDefault","type":"->","args":["[object] (Magento\\Cron\\Observer\\ProcessCronQueueObserver: {})","[object] (Magento\\Framework\\Event\\Observer: {})"]},{"file":"/home/*****/public_html/vendor/magento/framework/Event/Manager.php","line":66,"function":"dispatch","class":"Magento\\Framework\\Event\\Invoker\\InvokerDefault","type":"->","args":[{"instance":"Magento\\Cron\\Observer\\ProcessCronQueueObserver","name":"cron_observer"},"[object] (Magento\\Framework\\Event\\Observer: {})"]},{"file":"/home/*****/public_html/generated/code/Magento/Framework/Event/Manager/Proxy.php","line":95,"function":"dispatch","class":"Magento\\Framework\\Event\\Manager","type":"->","args":["default",[]]},{"file":"/home/*****/public_html/vendor/magento/framework/App/Cron.php","line":86,"function":"dispatch","class":"Magento\\Framework\\Event\\Manager\\Proxy","type":"->","args":["default"]},{"file":"/home/*****/public_html/vendor/magento/module-cron/Console/Command/CronCommand.php","line":117,"function":"launch","class":"Magento\\Framework\\App\\Cron","type":"->","args":[]},{"file":"/home/*****/public_html/vendor/symfony/console/Command/Command.php","line":255,"function":"execute","class":"Magento\\Cron\\Console\\Command\\CronCommand","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/vendor/magento/framework/Interception/Interceptor.php","line":58,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/vendor/magento/framework/Interception/Interceptor.php","line":138,"function":"___callParent","class":"Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor","type":"->","args":["run",["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]]},{"file":"/home/*****/public_html/vendor/magento/framework/Interception/Interceptor.php","line":153,"function":"Magento\\Framework\\Interception\\{closure}","class":"Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php","line":26,"function":"___callPlugins","class":"Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor","type":"->","args":["run",["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"],{"1":["newrelic-describe-commands"]}]},{"file":"/home/*****/public_html/vendor/symfony/console/Application.php","line":1001,"function":"run","class":"Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/vendor/symfony/console/Application.php","line":271,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor: {})","[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/vendor/magento/framework/Console/Cli.php","line":115,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/vendor/symfony/console/Application.php","line":147,"function":"doRun","class":"Magento\\Framework\\Console\\Cli","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: 'cron:run')","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"/home/*****/public_html/bin/magento","line":23,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[]}] []`

**Comment by lukawefocus** [comment]
@thomas-kl1 I see you've checked in a few changes 2 days ago. Testing your last version now. Erasing an account through admin seems to work. Data export works as well, now waiting for erasure of account in frontend. Keep you posted.

**Comment by lukawefocus** [comment]
@thomas-kl1 Ignore above, current version in branch 2.3 seems to work. Erasure in frontend works. 
Only 1 remark that could improve usability. In case an user is logged in, and cron job erased the account, the session is sitll alive. Account is accessible to this user as long as the session lives. User can see and changed anonymised information. It would be great if the session could be killed and account locked just before executing the anonymisation.

I'll be testing the notifications now and I will report any found bugs as a new issue. 

Thank you for your efforts so far!

**Comment by thomas-kl1** [comment]
@antoniocarboni @lukawefocus I'm closing this issue. If you have any bug, please create a new dedicated issue.

@lukawefocus thank you for your hard testing, it's helping me so much! I've pushed a commit to logout customers when their account has been erased. I'll backport the changes to the 2.3 branche.
